In [ ]:
a = 10
b = "10"
a = int(b)
print(a)
print(type(a))


10
<class 'int'>


# Numpy -- Numerical Python

In [1]:
import numpy as np

In [20]:
A = np.array([[1,2,3,4],
              [5,6,7,8]])
print(A)
print(A.shape) # Tells in aspedct of rows an dcolumns
print(A.size) # rows * colum
print(A.ndim) # A.ndim provides the dimension and no of axis
print(A.dtype) #

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
8
2
int64


In [21]:
A.shape


(2, 4)

In [22]:
A.size

8

In [23]:
A.ndim

2

In [24]:
A.dtype

dtype('int64')

In [27]:
B = np.arange(1 , 20 , 2) # when we include  parenthesis the upper limit is excluded and in square brackets the upper limit is included
B

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [32]:
C = np.zeros((2,3))
C

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
C.dtype

dtype('float64')

In [35]:
D = np.ones((2,4))
D

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
D.dtype

dtype('float64')

In [39]:
D = np.empty((2,4))
D

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
E = np.arange(15) .reshape((3,5))
E

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
var1 = np.array([20,30,40,50])
var2 = np.arange(4)
var3 = var1 - var2
var3

array([20, 29, 38, 47])

In [49]:
var1 < 35

array([ True,  True, False, False])

In [52]:
a = np.array([8 , 9 , 5 , 4 , 6 ])
b = np.array([4 , 8 , 5 , 6 , 7 ])

a + b
a - b
a * b
a / b
a % b

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a % b)

[12 17 10 10 13]
[ 4  1  0 -2 -1]
[32 72 25 24 42]
[2.         1.125      1.         0.66666667 0.85714286]
[0 1 0 4 6]


In [54]:
A = np.array([[1 , 0] ,
             [2 , 3]])
B = np.array([[1 , 1],
             [3 , 2]])


In [55]:
A * B

array([[1, 0],
       [6, 6]])

In [56]:
A @ B

array([[ 1,  1],
       [11,  8]])

In [57]:
 A.dot(B)

array([[ 1,  1],
       [11,  8]])